### ISSUE TITLE
Create game PUT request often doesn't return a response

### ISSUE THREAD

**Issue by OrangyTang** [casparluc/VikingDoom#4]
Submitting a PUT request to create a game often the server does not return a response, eventually the client times out.

Wireshark shows that the request is made successfully, but no response received.

Seems to happen most after a successful create game, then for the next hour or so I won't get a response until later (maybe the game times out on the server?)

Last failed requests seen at 10:17 GMT, 14th March.

Thanks.

**Comment by davinellulinvega** [comment]
Hello,

Thank you very much for your feedback.
You encountered an error, because you were trying to enter multiple games at the same time. Which by the rule is fine. However, an simple initialisation error in the subscribing process meant that the request was indefinitely trying to add your player to the same game. And that is impossible, even by the rules.
A solution has been implemented and deployed on the server. Could you please confirm that you do not encounter this particular problem anymore, before closing the issue.

Sincerely.

**Comment by OrangyTang** [comment]
Seems fixed now, thanks!
